<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import LoadingState from '../components/LoadingState.vue'; import QuestionCard from '../components/QuestionCard.vue'; import TtsControls from '../components/TtsControls.vue'
import { useExamStore } from '../stores/exam'; import { getTtsEngine } from '../services/ttsEngine'; import type { ChoiceLabel, PartNumber, QuestionGroup, ToeicTest } from '../types/exam'
const route=useRoute(); const store=useExamStore(); const testId=String(route.params.testId); const test=ref<ToeicTest>(); const part=ref<PartNumber>(Number(route.query.part||1) as PartNumber); const position=ref(0); const reveal=ref(false); const transcript=ref(false)
onMounted(async()=>{try{test.value=await store.ensureTest(testId)}catch{}}); onBeforeUnmount(()=>getTtsEngine().cancelSpeech()); watch([part,position],()=>{reveal.value=false;transcript.value=false;getTtsEngine().cancelSpeech()})
const wrongOnly=computed(()=>route.query.wrong==='1'); const groups=computed<QuestionGroup[]>(()=>{const source=test.value?.parts.find(p=>p.number===part.value)?.groups??[]; if(!wrongOnly.value)return source; const wrong=new Set(store.latestResults[testId]?.wrongQuestions??[]); return source.map(group=>({...group,questions:group.questions.filter(q=>wrong.has(q.id))})).filter(group=>group.questions.length)})
const current=computed(()=>groups.value[position.value]); const answered=computed(()=>current.value?.questions.every(q=>store.answers[testId]?.[q.id])??false)
function choose(id:number,value:ChoiceLabel){store.answer(testId,id,value)} function move(delta:number){position.value=Math.max(0,Math.min(groups.value.length-1,position.value+delta))}
</script>
<template><div class="page"><LoadingState :loading="store.loading" :error="store.error"/><template v-if="test"><div class="workspace-header"><div><p class="eyebrow">{{ wrongOnly ? 'Wrong answer practice' : 'Practice mode' }}</p><h1>Part {{ part }}</h1></div><RouterLink class="button quiet" :to="`/test/${testId}`">Exit practice</RouterLink></div><div class="part-tabs" role="tablist"><button v-for="n in 7" :key="n" :class="{active:part===n}" @click="part=n as PartNumber;position=0">Part {{ n }}<small>{{ n<5?'Listening':'Reading' }}</small></button></div><div v-if="current" class="practice-layout"><aside class="session-panel"><span class="progress-label">Set {{ position+1 }} of {{ groups.length }}</span><div class="progress"><i :style="{width:`${((position+1)/groups.length)*100}%`}"/></div><TtsControls :lines="current.speech.length?current.speech:current.questions[0]?.speech??[]"/><button v-if="current.speech.length" type="button" @click="transcript=!transcript">{{ transcript?'Hide':'Show' }} transcript</button><button class="primary" type="button" :disabled="!answered" @click="reveal=true">Check answers</button><p class="microcopy">Your answer is saved on this device as soon as you choose it.</p></aside><section class="questions-stack"><QuestionCard v-for="question in current.questions" :key="question.id" :question="question" :model-value="store.answers[testId]?.[question.id]" :reveal="reveal" :show-transcript="transcript" @update:model-value="choose(question.id,$event)"/><div class="pager"><button :disabled="position===0" @click="move(-1)">← Previous</button><button class="primary" :disabled="position===groups.length-1" @click="move(1)">Next set →</button></div></section></div><div v-else class="empty-state"><h2>No questions here yet</h2><p>{{ wrongOnly?'Complete an exam to build your wrong-answer list.':'This Part has no content.' }}</p></div></template></div></template>
